# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-15 15:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cajero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='logo')),
                ('direccion', models.CharField(max_length=200)),
                ('horario', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(max_length=50)),
                ('rfc', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Empresa',
            },
        ),
        migrations.CreateModel(
            name='Metodos_pago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Metodos de pago',
            },
        ),
        migrations.CreateModel(
            name='Sucursales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=50)),
                ('direccion', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Sucursales',
            },
        ),
        migrations.AddField(
            model_name='cajero',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='empresa.Sucursales'),
        ),
        migrations.AddField(
            model_name='cajero',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
